---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.18
    hooks:
      - id: shellcheck
        name: Shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        name: Markdownlint

  - repo: local
    hooks:
      - id: vagrant-validate
        name: Validate Vagrantfile
        description: Runs vagrant validate to validate Vagrantfiles
        language: system
        files: "Vagrantfile"
        entry: vagrant validate
      - id: packer-fmt
        name: Packer format
        description: Format all Packer configuration files to a canonical format
        language: script
        entry: hooks/packer-fmt.sh
        files: (\.pkr\.hcl|\.pkrvars\.hcl)$
      - id: packer-validate
        name: Packer validate
        description: Validates all Packer configuration files
        language: script
        entry: hooks/packer-validate.sh
        files: (\.pkr\.(hcl|json)|\.pkrvars\.hcl)$
