name: pre-commit

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Install Shellcheck
        run: |
          brew install shellcheck

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
