name: Release

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  VirtualBox:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Build VirtualBox
        run: |
          make build-vb
