name: Release

on:
  push:
    tags:
      - "*.*.*-*.*.*"

permissions:
  contents: write

jobs:
  VirtualBox:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Build VirtualBox
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG%-*} make build-vb

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: .output/*.box
